
name: Create a new release

on:
  pull_request:
      types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    defaults:
      run:
        shell: bash -l {0}
    name: Finish release
    runs-on: ubuntu-24.04 # latest LTS release
    concurrency:
      group: NEW_RELEASE
      cancel-in-progress: false # don't abort while we might be creating a PR or something
    steps:

      - uses: actions/checkout@v4
      - name: setup release PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |

          set -e
          PR_ID=$(gh pr list --state "open" --author "app/github-actions" --search "release"  --json "number" --jq '. | first | .number')
          gh pr merge $PR_ID

          # TODO:
          # - create tag
          # - publish to pypi, docker, conda
          # - create gh release
          # - publish docs
          # - make new commit with new `Unreleased` header in changelog, and set version back to dev
