
name: hydromt

channels:
    - conda-forge

dependencies:
- affine
- bottleneck
- click
- dask
- entrypoints
- fiona==1.8.22
- gdal>=3.1
- geopandas>=0.10
- netcdf4
- numpy>=1.20
- packaging
- pandas
- pyflwdir>=0.5.4
- pyproj
- rasterio
- rioxarray
- scipy
- shapely>=2.0.0
- universal_pathlib
- xarray
- xmltodict
- zarr
