name: Bug Report
description: Report incorrect behavior in the HydroMT library
title: "BUG: "
labels: [bug, needs refinement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: HydroMT version checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have checked that this bug exists on the latest version of HydroMT.   
          required: true
        - label: >
            I have checked that this bug exists on the main branch of HydroMT.            
  - type: textarea
    id: example
    attributes:
      label: Reproducible Example
      description: >
        Please provide a minimal, copy-pastable example to reproduce the behavior:
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Issue Description
      description: >
        Please provide a description of the issue shown in the reproducible example:
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Installed Versions
      description: >
        Please provide the version of HydroMT:
    validations:
      required: true
  - type: textarea
    id: Additional
    attributes:
      label: Additional context
      description: >
        Please add any other context about the bug here:
    validations:
      required: false
