---
name: Documentation Improvement
description: Report wrong or missing documentation
labels: [Documentation, Needs refinement]

body:
  - type: checkboxes
    attributes:
      label: HydroMT version checks
      options:
        - label: >
            I have checked that the issue still exists on the latest versions of the docs
            on `main` [here](https://github.com/Deltares/hydromt)
          required: true
  - type: dropdown
    id: kind
    attributes:
      label: Kind of issue
      description: What kind of documentation issue is this?
      options:
        - Docs are wrong
        - Docs are unclear
        - Docs are missing
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Location of the documentation
      description: >
        If the docs are wrong or unclear please provide the URL of the documentation in question:
  - type: textarea
    id: problem
    attributes:
      label: Documentation problem
      description: >
        Please provide a description of the documentation problem:
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested fix for documentation
      description: >
        Please explain your suggested fix and why it's better than the existing documentation:
