name: Feature Request
description: Suggest an idea for HydroMT
title: "ENHANCEMENT: "
labels: [enhancement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality to HydroMT
        - label: >
            Changing existing functionality in HydroMT
        - label: >
            Removing existing functionality in HydroMT
  - type: textarea
    id: description
    attributes:
      label: Enhancement Description
      description: >
        Please provide a clear and concise description of what your proposed enhancement is:
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please add add any other context about the enhancement here:
