---
name: Feature Request
description: Suggest an idea/enhancement for HydroMT
labels: [Enhancement, Needs refinement]

body:
  - type: dropdown
    id: checks
    attributes:
      label: Feature Type
      description: What kind of feature request is this?
      options:
        - Adding new functionality
        - Changing existing functionality
        - Removing existing functionality
  - type: textarea
    id: description
    attributes:
      label: Enhancement Description
      description: >
        Please provide a clear and concise description of the feature you're requesting:
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: >
        Please describe a situation in which this feature would be useful to you, with code or cli examples if possible.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please add any other context about the enhancement here:
