name: Create a new patch release

on:
  workflow_dispatch:
    inputs:
      release_branch:
        type: string
        description: "Release branch to patch (e.g. release/1.4)"
        required: true

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        shell: bash -l {0}
    name: Setup patch release PR
    runs-on: ubuntu-24.04
    concurrency:
      group: NEW_RELEASE
      cancel-in-progress: false
    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.release_branch }}

      - name: check the release branch exists
        run: |
          if ! git show-ref --verify --quiet "refs/remotes/origin/${{ inputs.release_branch }}"; then
            echo "Branch '${{ inputs.release_branch }}' does not exist."
            exit 1
          fi

      - name: check there are no pre-existing release PRs
        run: |
          export EXISTING_RELEASE_PR_NUMBER=$(gh pr list --search "release" --json "number")
          if [ $(echo $EXISTING_RELEASE_PR_NUMBER | jq '.|length') -gt 0]; then
            gh pr comment $EXISTING_RELEASE_PR_NUMBER --body "$username It looks like you tried to start a new release but this one is already started. Please either finish or close this one before continuing";
            exit 1
          fi
        env:
          username: ${{ github.actor }}

      - name: setup patch release PR
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_BRANCH: ${{ inputs.release_branch }}
        run: |
          set -e

          export CURRENT_VERSION=$(bash .github/scripts/get-version.sh)
          export CURRENT_MAJOR=$(echo $CURRENT_VERSION | cut -d'.' -f 1)
          export CURRENT_MINOR=$(echo $CURRENT_VERSION | cut -d'.' -f 2)
          export CURRENT_PATCH=$(echo $CURRENT_VERSION | cut -d'.' -f 3)

          export NEW_VERSION="$CURRENT_MAJOR.$CURRENT_MINOR.$((CURRENT_PATCH + 1))"

          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

          git pull

          bash .github/scripts/setup-release.sh "$NEW_VERSION" "$RELEASE_BRANCH"
