name: Finalise release

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash -l -e {0}

jobs:
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - id: download-artifact
        uses: dawidd6/action-download-artifact@v20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: create-release-artifacts.yml
          workflow_conclusion: success
          name: pypi-release-artifacts
          path: dist
          check_artifacts: true
          if_no_artifact_found: fail

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true

  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: download-artifact
        uses: dawidd6/action-download-artifact@v20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: create-release-artifacts.yml
          workflow_conclusion: success
          name: docs-release-artifacts
          path: docs/_build
          check_artifacts: true
          if_no_artifact_found: fail

      - name: Determine release version
        run: echo "DOC_VERSION=v$(bash .github/scripts/get-version.sh)" >> "$GITHUB_ENV"

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          exclude_assets: .buildinfo,_sources/*,_examples/*.ipynb
          destination_dir: ./${{ env.DOC_VERSION }}
          keep_files: false
          full_commit_message: Deploy Release ${{ env.DOC_VERSION }} docs to GitHub Pages

      - name: Update doc symlinks
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git checkout gh-pages
          ln -sfn "${{ env.DOC_VERSION }}" stable
          git add stable
          git commit -m "update symlinks"
          git push

  gh-release:
    name: Publish GitHub release
    needs:
      - publish-pypi
      - publish-docs
    runs-on: ubuntu-latest
    concurrency:
      group: NEW_RELEASE
      cancel-in-progress: false
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main

      - name: Publish github release
        run: |
          export RELEASE_VERSION=v$(bash .github/scripts/get-version.sh)
          if [ -z "$RELEASE_VERSION" ]; then
            echo "could not determine release version"
            exit 1
          fi

          awk '
          BEGIN { capture = 0; }
          /^v[0-9]+\.[0-9]+\.[0-9]+.*$/ { if (capture == 0) { capture = 1; } else { exit; } }
          capture { print; }
          ' docs/changelog.rst > release_notes.rst

          gh release create "$RELEASE_VERSION" \
            --title "$RELEASE_VERSION" \
            --notes-file release_notes.rst \
            --latest

      - name: Create post release PR
        run: |
          export RELEASE_VERSION=v$(bash .github/scripts/get-version.sh)

          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b "post-$RELEASE_VERSION-release"

          sed -i "s/$RELEASE_VERSION/Unreleased\n==========\n\nNew\n---\n\nChanged\n-------\n\nFixed\n-----\n\nDeprecated\n----------\n\n$RELEASE_VERSION/" docs/changelog.rst
          sed -i 's/__version__.*=.*"\(.*\)".*/__version__ = "\1.dev0"/' hydromt/__init__.py

          git add hydromt/__init__.py docs/changelog.rst
          git commit -m "Post release $RELEASE_VERSION"
          git push --set-upstream origin "post-$RELEASE_VERSION-release"

          gh pr create -B "main" -H "post-$RELEASE_VERSION-release" -t "Post $RELEASE_VERSION release cleanup" -b "Add new changelog headers and set version back to dev"
