name: Pixi auto update

on:
  schedule:
  # At 03:00 on day 3 of the month
    - cron: "0 3 3 * *"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "v0.15.2"
          cache: false
      - name: Update pixi lock file
        run: |
          rm pixi.lock
          pixi install
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pixi-lock
          title: Update pixi lock file
          commit-message: "Update `pixi.lock`"
          body: Update pixi dependencies to the latest version.
          author: "GitHub <noreply@github.com>"
