name: Pre-commit auto update
on:
  schedule:
    # At 03:00 on day 3 of the month
    - cron: "0 3 3 * *"
  # on demand
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: browniebroke/pre-commit-autoupdate-action@main
      # Use a PAT from the service account so the created PR triggers downstream
      # workflows. Events created by the default GITHUB_TOKEN are intentionally
      # ignored by other workflow triggers to prevent infinite recursive runs.
      - uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.DELTARES_SERVICE_ACCOUNT_PAT }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "Update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
          author: "GitHub <noreply@github.com>"
