
name: Update Version
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:


jobs:
  update_version:
    if: github.event_name == 'workflow_dispatch' || github.event.review.state == 'approved'
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: configure git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Fetch last release
        run: echo "LAST_RELEASE=$(git tag --list | tail -n 1)" >> $GITHUB_ENV
      - name: calculate number of commist since last release
        run: echo "NUM_COMMITS=$(($(git rev-list ${{ env.LAST_RELEASE }}..main | wc -l) + 1 ))" >> $GITHUB_ENV
      - name: update version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sed -i "s/__version__\s*=\s*\"\([0-9]\+\.[0-9]\+\.[0-9]\+\).dev[0-9]\+\"/__version__ = \"\1.dev1\"/" hydromt/__init__.py
          git add hydromt/__init__.py
          git commit -m "update version"
          git push origin ${{ github.ref_name}}
          gh pr comment ${{ github.ref_name }} -b "I've updated the version for you. Feel free to merge now!"
